spring:
  application:
    name: zeon-register

eureka:
  instance:
    prefer-ip-address: ${EUREKA_INSTANCE_PREFER_IP:true}
  client:
    service-url:
      defaultZone: ${SPRING_REGISTER_URL:http://localhost:8761/eureka}
    fetch-registry: ${EUREKA_CLIENT_FETCH_REGISTRY:true}
    register-with-eureka: ${EUREKA_CLINE_REGISTER_WITH_EUREKA:false}
