spring:
  application:
    name: zeon-system
  datasource:
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.postgresql.Driver}
    url: ${SPRING_DATASOURCE_URL:${SPRING_DATASOURCE_JDBC_URL:jdbc:postgresql://localhost:5432}/zeon_system?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=UTF-8&allowPublicKeyRetrieval=true}
    username: ${SPRING_DATA_SOURCE_USERNAME:admin}
    password: ${SPRING_DATA_SOURCE_PASSWORD:123456}
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}
      password: ${SPRING_DATA_REDIS_PASSWORD:123456}
      database: ${SPRING_DATA_REDIS_DATABASE:0}

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml   # Mapper XML 文件路径
  type-aliases-package: com.zeon.entity      # 实体类包
  configuration:
    log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl
    map-underscore-to-camel-case: true
logging:
  level:
    com.zeon: ${LOGGING_LEVEL:info}

threadpool:
  core-size: ${THREAD_POOL_CORE_SIZE:8}
  max-size: ${THREAD_POOL_MAX_SIZE:16}
  queue-capacity: ${THREAD_POOL_QUEUE_CAPACITY:1000}
  keep-alive-seconds: ${THREAD_POOL_KEEP_ALIVE_SECONDS:60}
  thread-name-prefix: common-task-

