server:
  port: 3000

spring:
  application:
    name: zeon-system
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/db?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: admin
    password: 123456

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml   # Mapper XML 文件路径
  type-aliases-package: com.zeon.entity      # 实体类包
  configuration:
    log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl
    map-underscore-to-camel-case: true
logging:
  level:
    com.zeon: debug
    com.zeon.dao: info

threadpool:
  core-size: 8
  max-size: 32
  queue-capacity: 100
  keep-alive-seconds: 60
  thread-name-prefix: common-task-


eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

