spring:
  application:
    name: zeon-gateway
  datasource:
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.postgresql.Driver}
    url: ${SPRING_DATASORUCE_URL:${SPRING_DATASOURCE_JDBC_URL:jdbc:postgresql://localhost:5432}/zeon_admin?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=UTF-8&allowPublicKeyRetrieval=true}
    username: ${SPRING_DATA_SOURCE_USERNAME:admin}
    password: ${SPRING_DATA_SOURCE_PASSWORD:123456}
server:
  port: 8080

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  type-aliases-package: com.zeon.web.entity
  configuration:
    log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl

logging:
  level:
    com.zeon.web: ${LOGGING_LEVEL:info}